In [1]:
# PYTORCH

In [2]:
# A tensor is a generalized matrix

In [3]:
# scalar, vector, matrix, tensor
# but a vector is technically a 1D tensor, matrix is  a 2D tensor those just
# have their own names already

In [4]:
# easiest to arrange data sets as tensors

In [5]:
#PyTorch Tensor Basics

In [6]:
import torch

In [7]:
import numpy as np

In [9]:
torch.__version__
#to check enviornment

'1.1.0'

In [10]:
arr = np.array([1,2,3,4,5])

In [11]:
print(arr)

[1 2 3 4 5]


In [12]:
arr.dtype

dtype('int32')

In [13]:
type(arr)

numpy.ndarray

In [15]:
#convert to a tensor
#this one only works with numpy
x = torch.from_numpy(arr)

In [16]:
type(x)

torch.Tensor

In [17]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [18]:
#other option

In [19]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [21]:
arr2d = np.arange(0.0,12.0)

In [22]:
arr2d = arr2d.reshape(4,3)

In [23]:
x2 = torch.from_numpy(arr2d)

In [24]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [25]:
#the functions used above retain the relationship between the 
#array and the tensor
arr[0] = 99

In [26]:
arr

array([99,  2,  3,  4,  5])

In [27]:
#so when we edit the original array the tensor will be affected
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [28]:
#to avoid this
my_arr = np.arange(0,10)

In [29]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
my_tensor = torch.tensor(my_arr)

In [34]:
my_other_tensor = torch.from_numpy(my_arr)

In [35]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [36]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [37]:
#now when we edit the original array used
my_arr[0] = 99

In [38]:
#this one will be affected
my_other_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [39]:
#and this one will not be
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [40]:
#Tensor basics part two

In [41]:
new_arr = np.array([1,2,3])

In [42]:
#difference between torch.tensor and torch.Tensor

In [43]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [47]:
#converts to floats
torch.Tensor(new_arr)
#same as calling torch.FloatTensor

tensor([1., 2., 3.])

In [52]:
#how to initialize tensors
torch.empty(2,2)
#will return a bunch of small values in the size tensor you requested

tensor([[ 0.0000e+00,  0.0000e+00],
        [-5.9351e+06,  4.5908e-41]])

In [51]:
#if you actually want zeros use this
torch.zeros(4,3,dtype=torch.int64)
#can specify data types dont have to

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [53]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [55]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [56]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [57]:
#can also convert a python list
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [58]:
#to change data type
my_tensor = torch.tensor([1,2,3])

In [59]:
my_tensor.dtype

torch.int64

In [61]:
my_tensor = my_tensor.type(torch.int32)

In [62]:
my_tensor.dtype

torch.int32

In [64]:
#creating tensors of random numbers

In [65]:
#random distribution between 0 and 1
torch.rand(4,3)

tensor([[0.4469, 0.4521, 0.0850],
        [0.0026, 0.1474, 0.2609],
        [0.3671, 0.3645, 0.9174],
        [0.6980, 0.8565, 0.4378]])

In [67]:
#randomly from standard normal distribution
torch.randn(4,3)

tensor([[-1.6066,  0.4368,  0.7592],
        [ 1.8900, -0.2513, -0.2817],
        [ 0.2052,  0.2932, -0.8332],
        [-0.2916,  0.6984,  1.1211]])

In [69]:
#rand between low and high and the size
#high is exclusive
torch.randint(low=0, high=10, size=(5,5))

tensor([[5, 1, 2, 3, 3],
        [5, 8, 0, 5, 4],
        [3, 4, 0, 7, 5],
        [3, 5, 1, 0, 6],
        [5, 7, 6, 8, 8]])

In [70]:
#random number tensors that follow an input size
x = torch.zeros(2,5)

In [71]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [72]:
#takes shape of x
torch.rand_like(x)

tensor([[0.8302, 0.5276, 0.6263, 0.6140, 0.8071],
        [0.5625, 0.5481, 0.7750, 0.5488, 0.8305]])

In [73]:
torch.randn_like(x)

tensor([[-1.3232, -0.7144, -0.2474,  0.0396,  1.5014],
        [ 0.9531, -0.4062,  0.6805,  1.3573, -2.1945]])

In [74]:
torch.randint_like(x, low=0, high=11)

tensor([[10.,  6., 10.,  7.,  1.],
        [ 0.,  9.,  9.,  0., 10.]])

In [76]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [77]:
#Tensor Operations

In [78]:
x = torch.arange(6).reshape(3,2)

In [79]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [80]:
x[1,1]

tensor(3)

In [81]:
#even when indexing you still get back tensor objects

In [82]:
x[:,1]

tensor([1, 3, 5])

In [84]:
#in order to retain vertical column shape of that index
x[:,1:]
#the extra : at end does that

tensor([[1],
        [3],
        [5]])

In [85]:
x = torch.arange(10)

In [86]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
#view and reshape do not actually change the object in memory
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [88]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [90]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# have to reassing to actaull change the shape
x = x.reshape(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [93]:
x = torch.arange(10)

In [94]:
z = x.view(2,5)

In [95]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [96]:
#z is now linked to x so if we change x z will change
x[0] = 999999

In [97]:
z

tensor([[999999,      1,      2,      3,      4],
        [     5,      6,      7,      8,      9]])

In [98]:
#this is actually convienent when working with neural networks

In [99]:
x = torch.arange(10)

In [102]:
#good when dealing with really large tensors to see the size
x.shape

torch.Size([10])

In [103]:
#by setting -1 pytorch will infer the second dimension
#also helpful with large tensors
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [104]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [105]:
#Tensor Arithmetic

In [106]:
a = torch.tensor([1.,2.,3.])

In [107]:
b = torch.tensor([4.,5.,6.])

In [109]:
#elementwise addition
a + b

tensor([5., 7., 9.])

In [110]:
# + is doing the same thing as this
torch.add(a,b)

tensor([5., 7., 9.])

In [111]:
a.mul(b)

tensor([ 4., 10., 18.])

In [112]:
#if you want to perform a reassignment along with operation
#a = a.mul(b) or all of the methods have a corresponding _ method that reassigns
a.mul_(b)

tensor([ 4., 10., 18.])

In [113]:
a

tensor([ 4., 10., 18.])

In [114]:
#matrix operations

In [115]:
a = torch.tensor([1.,2.,3.])

In [116]:
b

tensor([4., 5., 6.])

In [118]:
#elementwise, not true matrix multiplication
a * b

tensor([ 4., 10., 18.])

In [119]:
#dot product
a.dot(b)

tensor(32.)

In [120]:
#matrix muliltplication

In [121]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [122]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [123]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [124]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [125]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [127]:
#short hand, but not recommended to be used
a @ b

tensor([[56, 62],
        [80, 89]])

In [128]:
#euclidian norm or L2
#also called the magnitude of a vector
x = torch.tensor([2.,3.,4.,5.])

In [129]:
#L2 or euclidian norm
x.norm()

tensor(7.3485)

In [130]:
#number of elements
x.numel()

4

In [131]:
#works for 2d not 3d
len(x)

4